language: node_js
node_js:
  - 14
cache:
  directories:
    - node_modules

deploy:
  provider: npm
  email: open-source@goodeggs.com
  api_key:
    secure: "ZncCvIFucZSAjSJBXAkGfHsA0VpaH3GcmSeICDpBkAJ87TWXsQmPiEdTGV7t8cmtzPiAJCVWLXLR6wKKjHBw/N6AZbhHcObePpsRIwHE2RpZ/QYLiBJqYqP4WZW82KZSGfhh/b+Ukcah541cGvHqHJlWUtlfLd9xj1DogOHbJ1Q="
  clean_up: false
  on:
    tags: true
    all_branches: true
