language: node_js
node_js:
  - '0.10'
cache:
  directories:
    - node_modules

deploy:
  provider: npm
  email: open-source@goodeggs.com
  api_key:
    secure: "Yjcy7+ZidJo7KKpk1c4EpqCvW0FmRKggcdGH4ogX3mVU2zKfGoLjkiRBJw+tS5HrtI/fDk5pn0DU6kSPdUaXLNCOZ77KQ0PcmxZr4ywd976DitHa4C74c4Y4OPgMymJFKQTtmzYupCVOYgwo1YOwyPsAh2Ttrnw5vCtBcslKfLg="
  clean_up: false
  on:
    tags: true
    all_branches: true
